//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Circles()
        {
            this.MemorizationRecords = new HashSet<MemorizationRecords>();
        }
    
        public string CircleName { get; set; }
        public string MosqueName { get; set; }
        public Nullable<int> UserID { get; set; }
        public string EducationalLevel { get; set; }
        public string CircleLevel { get; set; }
        public int CircleID { get; set; }
        public Nullable<int> StudentsCount { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemorizationRecords> MemorizationRecords { get; set; }
    }
}
