//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemorizationRecords
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemorizationRecords()
        {
            this.NewMemorization = new HashSet<NewMemorization>();
            this.Revision = new HashSet<Revision>();
        }
    
        public int RecordID { get; set; }
        public System.DateTime SessionDate { get; set; }
        public System.TimeSpan SessionTime { get; set; }
        public int CircleID { get; set; }
        public int StudentID { get; set; }
        public string AttendanceStatus { get; set; }
        public string Notes { get; set; }
    
        public virtual Circles Circles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewMemorization> NewMemorization { get; set; }
        public virtual Students Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revision> Revision { get; set; }
    }
}
