//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewMemorization
    {
        public int NewMemID { get; set; }
        public int RecordID { get; set; }
        public string SuraFrom { get; set; }
        public string AyahFrom { get; set; }
        public string SuraTo { get; set; }
        public string AyahTo { get; set; }
        public Nullable<int> PagesCount { get; set; }
        public Nullable<int> Mistakes { get; set; }
    
        public virtual MemorizationRecords MemorizationRecords { get; set; }
    }
}
