//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.MemorizationRecords = new HashSet<MemorizationRecords>();
        }
    
        public string StudentName { get; set; }
        public Nullable<int> CircleID { get; set; }
        public string Nationality { get; set; }
        public string BirthDate { get; set; }
        public string GuardianPhone { get; set; }
        public string EducationalLevel { get; set; }
        public string phone { get; set; }
        public string addrass { get; set; }
        public int StudentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemorizationRecords> MemorizationRecords { get; set; }
    }
}
