//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment.circalDisplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceSessions
    {
        public int SessionID { get; set; }
        public Nullable<int> CircleID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<System.DateTime> SessionDate { get; set; }
        public Nullable<System.TimeSpan> SessionTime { get; set; }
        public string EducationalLevel { get; set; }
    }
}
