//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment.circalDisplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circles
    {
        public int CircleID { get; set; }
        public string CircleName { get; set; }
        public string MosqueName { get; set; }
        public string EducationalLevel { get; set; }
        public string CircleLevel { get; set; }
        public Nullable<int> StudentsCount { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Circles Circles1 { get; set; }
        public virtual Circles Circles2 { get; set; }
        public virtual Users Users { get; set; }
    }
}
