//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment.circalDisplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemorizationRecords
    {
        public long RecordID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string AttendanceStatus { get; set; }
        public string NewMemSuraFrom { get; set; }
        public Nullable<int> NewMemAyahFrom { get; set; }
        public string NewMemSuraTo { get; set; }
        public Nullable<int> NewMemPages { get; set; }
        public Nullable<int> NewMemMistakes { get; set; }
        public string RevSuraForm { get; set; }
        public Nullable<int> RevPages { get; set; }
        public Nullable<int> RevMistakes { get; set; }
        public string Notes { get; set; }
    }
}
