//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment.circalDisplay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Memorization_Circles_ManagementEntities6 : DbContext
    {
        public Memorization_Circles_ManagementEntities6()
            : base("name=Memorization_Circles_ManagementEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttendanceSessions> AttendanceSessions { get; set; }
        public virtual DbSet<Circles> Circles { get; set; }
        public virtual DbSet<MemorizationRecords> MemorizationRecords { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
