//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment.circalDisplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> CircleID { get; set; }
        public string Nationality { get; set; }
        public string BirthDate { get; set; }
        public string GuardianPhone { get; set; }
        public string EducationalLevel { get; set; }
        public string phone { get; set; }
        public string addrass { get; set; }
    }
}
